name: mnemonic
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  hex: ^0.2.0
  crypto: ^3.0.0

dev_dependencies:
  test: ^1.17.10
  lint: ^1.5.3